```{r setup, include=FALSE}
require(readr)
# Covariance matrix for noise "like" the given residuals.
#
# Assumes they were generated from a stationary process.
EmpiricalCovarianceMatrix <- function(residuals) {
  autocorrelation <- acf(residuals, lag.max=length(residuals))$acf
  sigma_sq <- var(residuals)
  return (outer(1:length(residuals), 1:length(residuals),
                function(a, b) { sigma_sq * autocorrelation[abs(a - b) + 1] }))
}

# Put quote marks around 'v'.
#
# No attempt is made to escape double quotes; caveat user!
Quotify <- function(v) {
  paste('"', v, '"', sep='')
}

# A string representing the given vector, suitable for javascript.
VectorToJavascript <- function(v) {
  paste(sep='', '[', paste(collapse=',', v), ']')
}

# A string representing the given matrix, suitable for javascript.
MatrixToJavascript <- function(m) {
  VectorToJavascript(apply(m, 1, VectorToJavascript))
}

# A matrix whose columns are the values of the supplied basis functions,
# evaluated at the supplied points x.
LinearLeastSquaresMatrix <- function(x, functions) {
  sapply(functions,
         function(f) {
           sapply(x, function(x) { f(x) })
         })
}

rss_file <- 'content/examples/trendlines/data/rss.csv'
d_rss <- read_csv(rss_file)
date_strings <- sprintf("%04d-%02d-01", d_rss$year, d_rss$month)
fit <- lm(d_rss$anomaly ~ as.Date(date_strings))
```

<script language='javascript'>
var residual_covariance = `r MatrixToJavascript(EmpiricalCovarianceMatrix(resid(fit)))`;
</script>

<div id='randomness'></div>

<div id='slopes'></div>

<div id='independentSlopes'></div>

<script type='text/javascript'>

// Load the Visualization API.
google.load('visualization', '1.0', {'packages': ['corechart']});
// Set a callback to run when the Google Visualization API is loaded.
google.setOnLoadCallback(loaded);

function loaded() {
  // The x-values where we have data.
  var x = `r VectorToJavascript(Quotify(date_strings))`.map(
    function(d) { return new Date(d); });
  var cutoff_date = new Date('1997-02-15');

  // The changing part of the data will be powered by a Gaussian Oscillator.
  // So at every timestep, the data will be purely random and independent
  // noise, but the points will move smoothly from timestep to timestep.
  var independenceTimeMs = 10000;
  var frameLengthMs = 250;
  var numTimesteps = Math.round(independenceTimeMs / frameLengthMs);
  var cscOscillator = compactSupportCovarianceOscillator(x.length,
                                                         numTimesteps);

  // Construct an object for the fake data.
  var randomData = animatedDataGenerator(x, {
    animatedNoise: cscOscillator,
    y: `r VectorToJavascript(predict(fit))`,
    noiseMatrix: Cholesky(`r MatrixToJavascript(
      EmpiricalCovarianceMatrix(resid(fit)))`),
    x_type: 'date',
  });

  // Build the models.
  var boundaryPoints = [Math.min(x), cutoff_date, Math.max(x)];
  function xDateOptions() {
    return { xFunc: function(x) { return new Date(x); } };
  }
  var badModel = linearModel(Object.assign(
    xDateOptions(),
    { bounds: [cutoff_date, Math.max(x)] }));
  badModel.label = 'Truncated trendline';
  badModel.id = 'truncated';
  var goodModel = piecewiseLinearModel(boundaryPoints.slice(1, -1), xDateOptions());
  goodModel.label = 'Connected trendlines';
  goodModel.id = 'connected';

  // For debugging only; can safely delete this once this works.
  x_peek = x;
  cscOscillator_peek = cscOscillator;
  randomData_peek = randomData;
  goodModel_peek = goodModel;
  boundaryPoints_peek = boundaryPoints;

  // Build a DataTable to hold all the data (both the random noise, and the
  // models which fit it).
  allData = animatedDataTable(randomData);
  allData.addAndTrainModel(badModel);
  allData.addAndTrainModel(goodModel);

  function baseChartOptions() {
    return {
      width: 800,
      vAxis: {
        viewWindow: {
          min: -0.5,
          max: 0.7,
        },
      },
      animation: {
        duration: frameLengthMs,
        easing: 'linear',
        startup: true,
      },
      height: 500
    };
  }

  // Construct a chart to show all these curves.
  var dataChart = new google.visualization.LineChart(document.getElementById('randomness'));
  var dataChartOptions = Object.assign(
      baseChartOptions(),
      {
        title: 'Trendlines: connected, vs. not',
        series: [],
      });
  dataChartOptions.series[seriesNumberWithId(allData.dataTable, 'disconnected')] = { color: 'red' };
  dataChartOptions.series[seriesNumberWithId(allData.dataTable, 'connected')] = { color: 'blue' };
  dataChartOptions.series[seriesNumberWithId(allData.dataTable, 'y')] = {
    color: '#888',
    lineWidth: 1,
  };

  function update() {
    dataChart.draw(allData.dataTable, dataChartOptions);
    allData.update();
  }
  var listenerId = google.visualization.events.addListener(dataChart, 'animationfinish', update);
  update();

  toggleAnimation = function() {
    if (listenerId == null) {
      listenerId = google.visualization.events.addListener(dataChart, 'animationfinish', update);
      update();
    } else {
      google.visualization.events.removeListener(listenerId);
      listenerId = null;
    }
  }
}


handleKeyPress = function(e) {
  e = e || window.event;
  switch (String.fromCharCode(e.keyCode)) {
    case 'p':
      toggleAnimation();
      break;
    default:
      return;
  }
}
document.addEventListener("keypress", handleKeyPress, false);

</script>
